### ISSUE TITLE
invalid date when uploading image without exif

### ISSUE THREAD

**Issue by benharri** [electricduck/atfile#3]
uploaded an image

```
date: invalid date ‘  +00:00’
date: invalid date ‘  +00:00’
```

this results in it being unviewable in a browser. it also seems to think this image is copyrighted?

**Comment by electricduck** [comment]
(Relating to this object: https://atproto-browser.vercel.app/at/did:plc:v7tbr6qxk6xanxzn6hjmbk7o/blue.zio.atfile.upload/3l76ts2x7l62i)

> this results in it being unviewable in a browser

Actually, this occurs to all uploads on that PDS (`bsky.social` / `*.bsky.network`)

>  it also seems to think this image is copyrighted?

This is a warning that flags up for everything as a reminder. It can be turned off with `ATFILE_SKIP_COPYRIGHT_WARN=1` in the config
